version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python model_training.py
      - echo "Model training completed"
artifacts:
  files:
    - model.pkl
