version: "3.9"

services:
  flask_app:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - ml_network
    volumes:
      - ./models:/models

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - ml_network
    volumes:
      - redis_data:/data

  worker:
    build: ./worker
    container_name: worker
    networks:
      - ml_network
    depends_on:
      - redis
    volumes:
      - ./logs:/logs
      - ./models:/models

  frontend:
    build: ./frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    networks:
      - ml_network
    depends_on:
      - flask_app

  busybox:
    image: busybox
    container_name: busybox_logger
    command: tail -f /logs/predictions.log
    networks:
      - ml_network
    depends_on:
      - worker
    volumes:
      - ./logs:/logs

volumes:
  redis_data:
  logs:
  models:

networks:
  ml_network:
    driver: bridge
