version: '3.9'
services:
  model_serving:
    build: ./model_serving
    container_name: model_serving
    ports:
      - "5001:5001"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5002:5002"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - app_network

  logger:
    build: ./logger
    container_name: logger
    volumes:
      - ./logs:/app/logs
    ports:
      - "5003:5003"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
