apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: purushotham1982/backend:latest
        ports:
        - containerPort: 8000
