apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ml-app2
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
  type: NodePort
